### ISSUE TITLE
Syntax highlighting: problems with tags

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown-vscode#3]
Hi!

Tags at the end of a line seem to affect syntax highlighting. E.g.
```
[These]
    - [Grund 1]: Text #con
    + [Grund 2]: Text
```
yields 
![grafik](https://user-images.githubusercontent.com/3662782/34309972-17848d6a-e755-11e7-8667-0cfe046e929d.png)
whereas, if a blank space is inserted after `#con`, we have
![grafik](https://user-images.githubusercontent.com/3662782/34309990-330e9b7a-e755-11e7-9d94-763518e1e0c1.png)

All sorts of syntax highlighting seem to be affected, e.g.,
```
[These]
    - [Grund 1]: Text #con
<!-- + [Grund 2]: Text -->
```
gives
![grafik](https://user-images.githubusercontent.com/3662782/34310045-88871014-e755-11e7-8e03-423362328bf5.png)

**Comment by christianvoigt** [comment]
fixed in 1.0.0
