### ISSUE TITLE
Export only works with folders, not with single files

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown-vscode#6]
If no folder is open in the VS code explorer (workspace is empty), but only a single argdown-file is opened in the editor, then the argdown export command yields:

```
Argdown language server initialized.
No workspace folder found.
[Error - 10:42:15] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with 
message: Cannot read property 'Symbol(Symbol.iterator)' of 
undefined
  Code: -32603
```

This will be counterintuitive for non-expert users. 

Maybe the default option of the export command should be to export the file opened in the active editor?

**Comment by christianvoigt** [comment]
should not longer be a problem in 1.0.0. If bug reappears, please repost it in the argdown repo.
