### ISSUE TITLE
Progress monitor export

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown-vscode#9]
As exports might take long, add a progress monitor.

https://code.visualstudio.com/updates/v1_22#_show-long-running-operations-as-notifications-with-cancellation-support

**Comment by christianvoigt** [comment]
At least for the near future, users should use VS Code for single-file exports and the cli for exporting whole folders. Doing the latter in VS Code is possible but "hidden" in the Command menu. Progress bars are only be needed for the latter case.
